version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    environment:
      - VIRTUAL_HOST=localhost
      - APP_ENV=dev